name: Build and publish docker images
on:
  push:
    branches:
      - main
jobs:
  build-publish-docker-images:
    name: build and publish docker image ${{ matrix.image }}
    strategy:
      max-parallel: 48
      fail-fast: false
      matrix:
        image: [ 'benchmark' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - run: |
          docker build --no-cache -f ./dockerfiles/Dockerfile.${{ env.image }} -t ${{ env.dockerhub_organization }}/fluent-bit-ci:${{ env.image }} .
          docker push ${{ env.dockerhub_organization}}/fluent-bit-ci:${{ env.image }}
        name: build and publish ${{ matrix.image }} image.
        env:
          image: ${{ matrix.image }}
          dockerhub_organization: fluentbitdev