---
name: Lint Pull Requests
on:
  pull_request:
    branches:
      - main
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: golang-lint for integration tests
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: integration
          args: --build-tags integration --timeout=10m
      - name: golang-lint for long running tests
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: long-run
          args: --build-tags integration --timeout=10m

  hadolint-pr:
    runs-on: ubuntu-latest
    name: Hadolint
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-hadolint@v1

  shellcheck-pr:
    runs-on: ubuntu-latest
    name: Shellcheck
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master

  actionlint-pr:
    runs-on: ubuntu-latest
    name: Actionlint
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: terraform format check
        run: >
          find ./ -name '*.tf' -exec dirname \{\} \; | sort | uniq |
          parallel terraform fmt -diff -check
