name: Run integration tests for PR
on:
  pull_request_target:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize
jobs:
  run-tests:
    name: Run integration tests
    uses: ./.github/workflows/call-run-integration-test.yaml
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    with:
      image_name: ghcr.io/fluent/fluent-bit/master
      image_tag: x86_64
      ref: ${{ github.event.pull_request.head.sha }}
    secrets:
      opensearch_aws_access_id: ${{ secrets.OPENSEARCH_AWS_ACCESS_ID }}
      opensearch_aws_secret_key: ${{ secrets.OPENSEARCH_AWS_SECRET_KEY }}
      opensearch_admin_password: ${{ secrets.OPENSEARCH_ADMIN_PASSWORD }}
      terraform_api_token: ${{ secrets.TF_API_TOKEN }}